package SpringMy.Maven.Utility;

import java.util.ArrayList;
import java.util.List;

public class SelectData {
	
	
	public List<String> genderData(){
		
		List<String> gerderList =new ArrayList<>();
		gerderList.add("Sex");
		gerderList.add("Female");
		gerderList.add("Male");
		return gerderList;
		
	}
	
   public List<String> countryData(){
	   
	   List<String> countryList =new ArrayList<>();
	   
	   countryList.add("Afghanistan");
	   countryList.add("Åland Islands");
	   countryList.add("Albania");
	   countryList.add("Algeria");
	   countryList.add("American Samoa");
	   countryList.add("Andorra");
	   countryList.add("Angola");
	   countryList.add("Anguilla");
	   countryList.add("Antarctica");
	   countryList.add("Antigua and Barbuda");
	   countryList.add("Argentina");
	   countryList.add("Armenia");
	   countryList.add("Aruba");
	   countryList.add("Australia");
	   countryList.add("Austria");
	   countryList.add("Azerbaijan");
	   countryList.add("Bahamas");
	   countryList.add("Bahrain");
	   countryList.add("Bangladesh");
	   countryList.add("Barbados");
	   countryList.add("Belarus");
	   countryList.add("Belgium");
	   countryList.add("Belize");
	   countryList.add("Benin");
	   countryList.add("Bermuda");
	   countryList.add("Bhutan");
	   countryList.add("Bolivia, Plurinational State of");
	   countryList.add("Bonaire, Sint Eustatius and Saba");
	   countryList.add("Bosnia and Herzegovina");
	   countryList.add("Botswana");
	   countryList.add("Bouvet Island");
	   countryList.add("Brazil");
	   countryList.add("British Indian Ocean Territory");
	   countryList.add("Brunei Darussalam");
	   countryList.add("Bulgaria");
	   countryList.add("Burkina Faso");
	   countryList.add("Burundi");
	   countryList.add("Cambodia");
	   countryList.add("Cameroon");
	   countryList.add("Canada");
	   countryList.add("Cape Verde");
	   countryList.add("Cayman Islands");
	   countryList.add("Central African Republic");
	   countryList.add("Chad");
	   countryList.add("Chile");
	   countryList.add("China");
	   countryList.add("Christmas Island");
	   countryList.add("Cocos (Keeling) Islands"); 
	   countryList.add("Colombia");
	   countryList.add("Comoros");
	   countryList.add("Congo");
	   countryList.add("Congo, the Democratic Republic of the");
	   countryList.add("Cook Islands");
	   countryList.add("Costa Rica");
	   countryList.add("Côte d'Ivoire");
	   countryList.add("Croatia");
	   countryList.add("Cuba");
	   countryList.add("Curaçao");
	   countryList.add("Cyprus");
	   countryList.add("Czech Republic");
	   countryList.add("Denmark");
	   countryList.add("Djibouti");
	   countryList.add("Dominica");
	   countryList.add("Dominican Republic");
	   countryList.add("Ecuador");
	   countryList.add("Egypt");
	   countryList.add("El Salvador");
	   countryList.add("Equatorial Guinea");
	   countryList.add("Eritrea");
	   countryList.add("Estonia");
	   countryList.add("Ethiopia");
	   countryList.add("Falkland Islands (Malvinas)");
	   countryList.add("Faroe Islands");
	   countryList.add("Fiji");
	   countryList.add("Finland");
	   countryList.add("France");
	   countryList.add("French Guiana");
	   countryList.add("French Polynesia");
	   countryList.add("French Southern Territories");
	   countryList.add("Gabon");
	   countryList.add("Gambia");
	   countryList.add("Georgia");
	   countryList.add("Germany");
	   countryList.add("Ghana");
	   countryList.add("Gibraltar");
	   countryList.add("Greece");
	   countryList.add("Greenland");
	   countryList.add("Grenada");
	   countryList.add("Guadeloupe");
	   countryList.add("Guam");
	   countryList.add("Guatemala");
	   countryList.add("Guernsey");
	   countryList.add("Guinea");
	   countryList.add("Guinea-Bissau");
	   countryList.add("Guyana");
	   countryList.add("Haiti"); 
	   countryList.add("Heard Island and McDonald Islands");
	   countryList.add("Holy See (Vatican City State)");
	   countryList.add("Honduras");
	   countryList.add("Hong Kong");
	   countryList.add("Hungary");
	   countryList.add("Iceland");
	   countryList.add("India");
	   countryList.add("Indonesia");
	   countryList.add("Iran, Islamic Republic of");
	   countryList.add("Iraq");
	   countryList.add("Ireland");
	   countryList.add("Isle of Man");
	   countryList.add("Israel");
	   countryList.add("Italy");
	   countryList.add("Jamaica");
	   countryList.add("Japan");
	   countryList.add("Jersey");
	   countryList.add("Jordan");
	   countryList.add("Kazakhstan");
	   countryList.add("Kenya");
	   countryList.add("Kiribati");
	   countryList.add("Korea, Democratic People's Republic of");
	   countryList.add("Korea, Republic of");
	   countryList.add("Kuwait");
	   countryList.add("Kyrgyzstan");
	   countryList.add("Lao People's Democratic Republic");
	   countryList.add("Latvia");
	   countryList.add("Lebanon");
	   countryList.add("Lesotho");
	   countryList.add("Liberia");
	   countryList.add("Libya");
	   countryList.add("Liechtenstein");
	   countryList.add("Lithuania");
	   countryList.add("Luxembourg");
	   countryList.add("Macao");
	   countryList.add("Macedonia, the former Yugoslav Republic of");
	   countryList.add("Madagascar");
	   countryList.add("Malawi");
	   countryList.add("Malaysia");
	   countryList.add("Maldives");
	   countryList.add("Mali");
	   countryList.add("Malta");
	   countryList.add("Marshall Islands");
	   countryList.add("Martinique");
	   countryList.add("Mauritania");
	   countryList.add("Mauritius");
	   countryList.add("Mayotte");
	   countryList.add("Mexico"); 
	   countryList.add("Micronesia, Federated States of");
	   countryList.add("Moldova, Republic of");
	   countryList.add("Monaco");
	   countryList.add("Mongolia");
	   countryList.add("Montenegro");
	   countryList.add("Montserrat");
	   countryList.add("Morocco");
	   countryList.add("Mozambique");
	   countryList.add("Myanmar");
	   countryList.add("Namibia");
	   countryList.add("Nauru");
	   countryList.add("Nepal");
	   countryList.add("Netherlands");
	   countryList.add("New Caledonia");
	   countryList.add("New Zealand");
	   countryList.add("Nicaragua");
	   countryList.add("Niger");
	   countryList.add("Nigeria");
	   countryList.add("Niue");
	   countryList.add("Norfolk Island");
	   countryList.add("Northern Mariana Islands");
	   countryList.add("Norway");
	   countryList.add("Oman");
	   countryList.add("Pakistan");
	   countryList.add("Palau");
	   countryList.add("Palestinian Territory, Occupied");
	   countryList.add("Panama");
	   countryList.add("Papua New Guinea");
	   countryList.add("Paraguay");
	   countryList.add("Peru");
	   countryList.add("Philippines");
	   countryList.add("Pitcairn");
	   countryList.add("Poland");
	   countryList.add("Portugal");
	   countryList.add("Puerto Rico");
	   countryList.add("Qatar");
	   countryList.add("Réunion");
	   countryList.add("Romania");
	   countryList.add("Russian Federation");
	   countryList.add("Rwanda");
	   countryList.add("Saint Barthélemy");
	   countryList.add("Saint Helena, Ascension and Tristan da Cunha");
	   countryList.add("Saint Kitts and Nevis");
	   countryList.add("Saint Lucia");
	   countryList.add("Saint Martin (French part)");
	   countryList.add("Saint Pierre and Miquelon");
	   countryList.add("Samoa");
	   countryList.add("San Marino");
	   countryList.add("Sao Tome and Principe");
	   countryList.add("Saudi Arabia");
	   countryList.add("Senegal");
	   countryList.add("Serbia");
	   countryList.add("Seychelles");
	   countryList.add("Sierra Leone");
	   countryList.add("Singapore");
	   countryList.add("Sint Maarten (Dutch part)");
	   countryList.add("Slovakia");
	   countryList.add("Slovenia");
	   countryList.add("Solomon Islands");
	   countryList.add("Somalia");
	   countryList.add("South Africa");
	   countryList.add("South Georgia and the South Sandwich Islands");
	   countryList.add("South Sudan");
	   countryList.add("Spain");
	   countryList.add("Sri Lanka");
	   countryList.add("Sudan");
	   countryList.add("Suriname");
	   countryList.add("Svalbard and Jan Mayen");
	   countryList.add("Swaziland");
	   countryList.add("Sweden");
	   countryList.add("Switzerland");
	   countryList.add("Syrian Arab Republic");
	   countryList.add("Taiwan, Province of China");
	   countryList.add("Tajikistan");
	   countryList.add("Tanzania, United Republic of");
	   countryList.add("Thailand");
	   countryList.add("Timor-Leste");
	   countryList.add("Togo");
	   countryList.add("Tokelau");
	   countryList.add("Tonga");
	   countryList.add("Trinidad and Tobago");
	   countryList.add("Tunisia");
	   countryList.add("Turkey");
	   countryList.add("Turkmenistan");
	   countryList.add("Turks and Caicos Islands");
	   countryList.add("Tuvalu");
	   countryList.add("Uganda");
	   countryList.add("Ukraine");
	   countryList.add("United Arab Emirates");
	   countryList.add("United Kingdom");
	   countryList.add("United States");
	   countryList.add("United States Minor Outlying Islands");
	   countryList.add("Uruguay");
	   countryList.add("Uzbekistan");
	   countryList.add("Vanuatu");
	   countryList.add("Venezuela, Bolivarian Republic of");
	   countryList.add("Viet Nam");
	   countryList.add("Virgin Islands, British");
	   countryList.add("Virgin Islands, U.S.");
	   countryList.add("Wallis and Futuna");
	   countryList.add("Western Sahara");
	   countryList.add("Yemen");
	   countryList.add("Zambia");
	   countryList.add("Zimbabwe");
	   
		return countryList;
		
	}

}
